// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqioctjrqnvfuwsnqrje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxaW9jdGpycW52ZnV3c25xcmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjM2MzksImV4cCI6MjA2NDQzOTYzOX0.7F7X_d3SFnPCXLLD5g8LKlP-QYjALeh0-pfgesXCMGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);